export {default as Home} from './home'
export {default as Movies} from './movies'
export {default as NotFound} from './notFound'
export {default as Search} from './search'
export {default as Serials} from './serials'